spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "194389107542-6cis8i2gk6pprnr3tp0v35plef4ugfov.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile

          kakao:
            client-id: "ba49c26dd38cad49345dd2a711abea9d"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
            client-name: Kakao

          naver:
            client-id: "GybhYcwwcaFAqsUM8brx"
            client-secret: "6gKizl4v4Z"
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, update, none 중 선택
    show-sql: true