name: Java CD (Gradle + Spring Boot)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create application-prod.yml from secrets
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml

    - name: Grant execute permission to Gradle
      run: chmod +x ./gradlew

    - name: Build JAR with Gradle (exclude test)
      run: ./gradlew clean bootJar -x test

    - name: Fix jar name (hidaddy.jar로 고정)
      run: |
        JAR=$(ls build/libs/*.jar | head -n1)
        mv "$JAR" build/libs/hidaddy.jar
        ls -al build/libs

    - name: Write SSH key to file (in workspace)
      run: |
        cat > ./deploy.pem <<'EOF'
        ${{ secrets.EC2_KEY }}
        EOF
        chmod 600 ./deploy.pem

    - name: Upload JAR and Service File to server (root)
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: root
        key_path: ./deploy.pem
        source: "build/libs/hidaddy.jar, deploy/hidaddy.service"
        target: /root 

    - name: Deploy on server (systemd, root)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: root
        key_path: ./deploy.pem
        script: |
          if ! command -v java >/dev/null 2>&1; then
            apt-get update -y && apt-get install -y openjdk-17-jre
          fi
          mv -f /root/hidaddy.service /etc/systemd/system/hidaddy.service
          systemctl daemon-reload
          systemctl enable hidaddy
          systemctl restart hidaddy
          systemctl status hidaddy --no-pager 