name: Java CI/CD

on:
  push:
    branches: [ main ]  # main 브랜치에 push될 때 작동

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Upload JAR to EC2
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: target/bloomway-0.0.1-SNAPSHOT.jar
        target: /home/ubuntu/app/

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          pkill -f 'bloomway-0.0.1-SNAPSHOT.jar' || true
          nohup java -jar /home/ubuntu/app/bloomway-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > /home/ubuntu/app/app.log 2>&1 &
