name: Java CI/CD

on: 
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle (실행 가능한 JAR 생성)
      run: ./gradlew clean bootJar -x test

    - name: JAR 파일 생성 확인
      run: ls -al build/libs

    - name: Upload JAR and Service File to EC2
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: build/libs/*.jar
        target: /home/ubuntu

    - name: Deploy on EC2 (서비스 등록 및 재시작)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo mv /home/ubuntu/hidady.service /etc/systemd/system/hidady.service
          sudo systemctl daemon-reload
          sudo systemctl enable hidady
          sudo systemctl restart hidady
          sudo systemctl status hidady --no-pager
